### ISSUE TITLE
Change the default position of pop-up windows

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#40] opened 2022-10-25 17:49 UTC
Suggested improvement.
Change the default position of pop-up windows (search & replace, go to page, go to scene, etc.) so that they do not cover the text on the page. A window could 'remember' the last position when activated again or simply be positiones on the side.

**Comment by Cerabbite** [comment] 2022-12-18 13:32
Is this position good?
![image](https://user-images.githubusercontent.com/98265679/208301180-17f9da9c-522c-46f8-9712-8e70c304d7bc.png)

**Comment by limburgher** [comment] 2022-12-21 20:48
That's a static location, or is it movable by the user?

**Comment by Cerabbite** [comment] 2022-12-21 21:22
It is movable, but it does not save the position

**Comment by limburgher** [comment] 2022-12-21 21:23
@maccagnan what do you think? Seems like a solid improvement to me.

**Comment by maccagnan** [comment] 2022-12-21 23:49
@Cerabbite  What do you mean by 'it doesn't save the position'? 
If that is the new default position it'd be great. It could save the last position used too, but that'd be a plus IMHO.

**Comment by Cerabbite** [comment] 2022-12-22 05:21
That is the new position, but it does not save the last position the user left it in.

**Comment by maccagnan** [comment] 2022-12-22 05:23
Definite Improvement.

**Comment by limburgher** [comment] 2023-01-04 20:25
Then I say let's go with it for now.

**Comment by Cerabbite** [comment] 2023-01-04 21:52
I will have to make sure that all popups are in that position, and than I will create the pull request

**Comment by Cerabbite** [comment] 2023-01-15 08:43
These are the popups I found (if I missed some please let me know):
- [ ] Settings Dialog
- [ ] Find and Replace
- [ ] Auto-completion
- [ ] Headers
- [ ] Locations (Trying to open this gives me this error: TypeError: __deepcopy__() takes 1 positional argument but 2 were given)
- [ ] Title Pages
- [ ] Spell checker dictionary
- [ ] Report type
- [ ] Character map
- [ ] Watermarked PDF's generator
- [ ] Commands

Do we want all of these to be in the top left corner or can some stay in the middle?

**Comment by maccagnan** [comment] 2023-01-15 18:28
I'd say all in the top left corner since the page will be normally showing the screenplay.

**Comment by Cerabbite** [comment] 2023-01-16 07:06
I opened a pull request (#50 ), I believe I have all the popups in the top left corner now. If you find one that is still in the center please let me know.

**Comment by limburgher** [comment] 2023-02-01 14:29
@Cerabbite I just released 2.4.8 and at least Find is still centered.

**Comment by Cerabbite** [comment] 2023-02-01 15:36
Weird, could you send a screenshot? On my device it is not centered

**Comment by limburgher** [comment] 2023-02-01 15:39
![Screenshot from 2023-02-01 09-38-44](https://user-images.githubusercontent.com/2363820/216089295-b534710a-4248-4386-9d6b-6aafed7e35ca.png)

**Comment by Cerabbite** [comment] 2023-02-01 15:49
I'll take a look to see if I can solve the problem but for me it is not centered

![image](https://user-images.githubusercontent.com/98265679/216092895-ad49fd75-b307-4fee-a501-90b00f6274c7.png)

**Comment by Cerabbite** [comment] 2023-02-01 15:53
Could you check for other dialogs? If they are all centered it could be, because the default popup position on Linux is center and on windows in the top right corner

**Comment by limburgher** [comment] 2023-02-01 18:36
Yeah, they're all centered and immobile.

**Comment by Cerabbite** [comment] 2023-02-01 19:19
Thanks for letting me know, I'll see how I can fix it

**Comment by Cerabbite** [comment] 2023-02-02 16:36
This is where I have positioned it right now. What I have changed is that instead of placing it in the default location I now place it 80 by 80 pixels from the topleft corner of the window. Note: This is currently only implemented in the find dialog. [Link to PR](https://github.com/Cerabbite/trelby/tree/Change-default-pos-popup-window)
![image](https://user-images.githubusercontent.com/98265679/216384713-d3213e1c-427d-4a3f-885d-afc0f6e46839.png)

**Comment by limburgher** [comment] 2023-02-02 16:50
Still centered for me: 
![image](https://user-images.githubusercontent.com/2363820/216388664-ee6e7f24-2798-4034-abae-48b08b938e77.png)

**Comment by maccagnan** [comment] 2023-02-02 20:08
I don't know if this is helpful, but back on Trelby 2.3 (python2) changing the Find window's position would work on a virtual machine but the same modification would not work on an installed distro.

**Comment by Cerabbite** [comment] 2023-02-02 20:43
Interesting

**Comment by limburgher** [comment] 2023-03-21 20:55
@Cerabbite any updates on this?

**Comment by Cerabbite** [comment] 2023-03-22 21:34
No, from everything that I could find my code should work on Linux. At the moment I am spread very thin, so once I have more time I will take a look at this again to see if I can finally solve it

**Comment by limburgher** [comment] 2023-03-23 13:58
No worries, thanks!

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
