### ISSUE TITLE
CI pipelines for Python 3.8 and 3.9 fail installing Python depdendencies

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#87] opened 2023-11-06 09:28 UTC
Those pipelines currently general fail. It seems like they fail when pip is self-updating:

```
 Successfully uninstalled pip-23.0.1
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  WARNING: The scripts pip, pip3 and pip3.8 are installed in '/opt/trelby/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed pip-23.3.1 wheel-0.41.3
WARNING: There was an error checking the latest version of pip.
/opt/hostedtoolcache/Python/3.8.18/x64/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
```

Example: https://github.com/limburgher/trelby/actions/runs/6761271733/job/18375981307?pr=84

From my understadning, the updated `pip` falsely gets installed into `/opt/trelby/bin`, which is not in `PATH`. Or is it supposed to be installed there, but this directory should be in `PATH`?

**Comment by janopae** [comment] 2023-11-06 09:28
@jonafato do you have an idea what goes wrong here?

**Comment by janopae** [comment] 2023-11-06 09:32
I just found https://github.com/limburgher/trelby/pull/66/files, which adds `/opt/trelby/bin` to `PATH` (so it seems like the installation directory is correct, and it should be in PATH). Maybe it is sufficient to move the lines inserted in #66 up before the `python -m pip install --upgrade pip` command is executed.

**Comment by txtsd** [comment] 2023-11-06 12:24
pip itself should not be in that directory. It should either be in a venv or system pip should be used.

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
