### ISSUE TITLE
Trelby v2.5

### ISSUE THREAD

**Issue by Cerabbite** [limburgher/trelby#45] opened 2022-12-18 14:43 UTC
This a list of things I think should be fixed/added for version 2.5
- [x] #11 
- [x] #15 
- [x] #20 
- [x] #31 
- [x] #32 
- [x] #40 
- [x] #41 
- [x] #42

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
