### ISSUE TITLE
Closing script within Trelby still results in wrong confusing confirmation message

### ISSUE THREAD

**Issue by Cerabbite** [limburgher/trelby#52] opened 2023-01-19 20:51 UTC
In #32 we changed the save dialogue for when exiting with unsaved changes. But the window has not changed when closing a script internally.
![image](https://user-images.githubusercontent.com/98265679/213556973-c935940e-6f7f-4246-9fc1-1d40d94cbf43.png)

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
