### ISSUE TITLE
Merge "copy" functionalities

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#31] opened 2022-09-04 10:57 UTC
Currently, Trelby has two copy features: One internal one, that copies the selection preserving its format but doesn't allow pasting into other applications, and one "system" one, that copies the selection as plain text and allows pasting system wide.

As Clipboards on all major operating systems support setting a MIME type to the clipboard entry, and even allow copying multiple versions in different MIME types at the same time, I propose using these instead:

So when copying, we copy both, a "text/plain" version, and a "text/trelby" version. Other applications will ignore the "text/trelby" version as they don't support this MIME type, while Trelby could use it while pasting.

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
