### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#29] opened 2022-08-19 21:19 UTC
wxWidgets luckily provides High-DPI scaling transparently. However, there are still some issues to be resolved for "full" High DPI support:

- [x] tab bar: The tab bar didn't render in high dpi due to double buffering issues. #23 already resolved this bug for for the tab bar.
- [ ] the character map seems to still suffer from a similar issue:
![grafik](https://user-images.githubusercontent.com/8160319/185707899-1d8b36b8-34b2-42c3-8588-55252e0b972b.png)
- [ ] Icons: We still ship the same low-res icons we shipped for the last 15 years. I propose removing them from the repo and switching to Adwaita icons: https://pypi.org/project/wx-icons-adwaita/ 
![grafik](https://user-images.githubusercontent.com/8160319/185708126-b594fe13-e62f-40f9-b066-9f018276384a.png)
- [ ] The application icon: The trelby icon in the title bar is small on High DPI displays – according to https://github.com/wxWidgets/wxWidgets/issues/22807, this is a Gtk bug: 
![grafik](https://user-images.githubusercontent.com/8160319/185708329-87d80146-a29d-45b5-a647-00b5803a713b.png)

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
