### ISSUE TITLE
Italics and underlined text

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#42] opened 2022-10-25 17:53 UTC
Suggested improvement.
Allowing italics, bold, and underlined for single words in action/description and dialogue. While microdirecting actors is in general a bad idea, at times it would be useful to add intention.

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
