### ISSUE TITLE
Be able to build or provide an 'Appimage' release for near universal Linux portability and compatibility.

### ISSUE THREAD

**Issue by batman1138** [limburgher/trelby#78] opened 2023-08-31 05:08 UTC
There are various forms of Linux out there and many do not support Trelby clean out of the box, especially if needed to run on read-only distros like SteamOS 3 on Steam Deck. (unless you disable the read-only, but that's a temporary measure as everything gets scrubbed and overwritten in the next update)

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
