### ISSUE TITLE
Publish Flatpak to Flathub?

### ISSUE THREAD

**Issue by ttang4299** [limburgher/trelby#54] opened 2023-02-15 17:51 UTC
I own a Steam Deck and it seems as though Flatpaks are the preferred way of installing new apps as well as keeping them updated. I've been doing a lot of work lately on my Steam Deck, and it would be nice to be able to install Trelby without relying on terminal commands. Please consider develpping a Flatpak version.

**Comment by janopae** [comment] 2023-06-06 11:58
Sadly, I think supporting all the security features of Flatpak (using portals and on-demand permissions for every access to the host system like opening and saving files) doesn't seem really possible with wxWidgets currently.

But we could make an "unsafe Flatpak" that requires full system access as a permission. That kind of perverts the idea of Flatpak, but a lot of applications do that currently, and that would be a way to make the app available to more users.

When reading this issue, I often asked myself which runtime to use, and how to provide our dependencies. There is no wxWidgets runtime, but a Gnome and a KDE runtime. wxWidgets uses Gtk, so the Gnome runtime would probably help us, but it would also contain a lot of stuff we don't need.

Maybe we should take a look at how other wxWidgets applications handle this. One interesting one would be Audacity. I think they use the Gnome runtime and build wxWidgets themselves.

**Comment by ttang4299** [comment] 2023-06-11 19:26
Yeah @janopae , I would be in support of an "unsafe Flatpak" and I'm pretty sure I'm already working with a few anyways, using Flatseal to help with permissions. The most important thing is being able to update as many of my apps as I can from one place, and that place is Flathub to me.

**Comment by ttang4299** [comment] 2023-06-11 19:26
Accidentally closed the issue, reopened it

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
