### ISSUE TITLE
View options

### ISSUE THREAD

**Issue by TheScooterKing** [limburgher/trelby#20] opened 2022-04-14 18:30 UTC
I'm a bit visually impaired, so it would be useful to me to see a view option for zoom, or even just fit to page width.

Glad to see that you've taken up the torch with this app.

**Comment by limburgher** [comment] 2022-04-19 18:53
I agree, this would be a great feature.

And thank you. :)

**Comment by janopae** [comment] 2023-04-07 15:19
@TheScooterKing Are you still waiting for this feature?

I'm asking because before we can implement zooming, we need to implement horizontal scrolling. There are 2 approaches to do this, one is a bit more "hacky" but will be pretty easy to implement, the other approach (#72) needs a huge restructuring of a lot of code, but leads to a more clean result and also a lot of other features "for free".

If I don't know whether there are even users who need this feature, I'll probably just try every now and then to continue my experiment with the huge solution, and not start any other attempts until that is finished (maybe never). If I knew there are still users waiting for this, I'd take a more realistic approach that could bring zooming to the Trelby canvas in the foreseeable future.

**Comment by ClaudiusMinimus** [comment] 2023-09-02 16:40
Thank you for porting this new version!
Adding a way to make the screen more readable would help my 66-year-old eyes.

**Comment by janopae** [comment] 2023-09-17 14:06
@ClaudiusMinimus Thanks for the feedback! Then I'm going to attempt to implement it in the simpler way. I hope to get zoom working during the next weeks.

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
