### ISSUE TITLE
Don't save settings when faulty

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#81] opened 2023-09-17 14:00 UTC
The script settings dialogue (and maybe also the general settings dialogue?) currently show message boxes when the configuration is faulty and is going to be applied, but still applies the faulty configuration (and exists the dialogue).

This is because the `checkForErrors` methods of settings pages don't have a way to interfere with the application of the settings – it can show message boxes, but it has no return value whatsoever that signals its callers that there were errors.

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
