### ISSUE TITLE
Support MacOs

### ISSUE THREAD

**Issue by Cerabbite** [limburgher/trelby#62] opened 2023-03-15 12:44 UTC
I think that it would be good to create builds for macOS so we support all platforms.

I think this is also a great time to see if we could build the binaries using Github Actions.

**Comment by janopae** [comment] 2023-04-07 12:52
My attempt to even run Trelby on MacOS:

- using the default python version on MacOS Ventura doesn't work, the attrdict error with wxWidgets but it's unsolvable as `pip3 install attrdict3` doesn't seem to fix it at this python version
- using the brew version of python (3.11 currently) doesn't seem to work as well (at first glance) because the version is too new and there are no built wxPython wheels and building it myself fails with no good error message (log file is not where it's supposed to be)
- everyone recommends to use pyenv anyway, and indeed wxWidgets installs like a charm on python 3.10 in pyenv, but pyenv python can't connect to the MacOS windowing system
- ended up using the system python installed from brew (3.11) again, but install wxPython also via brew (`brew install wxpython`). This indeed got me further, but it exposes what seems to be a font-related problem on MacOS:

```
python3 bin/trelby
Traceback (most recent call last):
  File "/Volumes/Projekte/trelby/src/trelby.py", line 2606, in OnInit
    refreshGuiConfig()
  File "/Volumes/Projekte/trelby/src/trelby.py", line 61, in refreshGuiConfig
    cfgGui = config.ConfigGui(cfgGl)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Projekte/trelby/src/config.py", line 1353, in __init__
    fi.font = wx.Font(nfi)
              ^^^^^^^^^^^^
wx._core.wxAssertionError: C++ assertion ""m_info.GetPointSize() > 0"" failed at ./src/osx/carbon/font.cpp(332) in Alloc(): Point size should not be zero.
```

So note to myself for further attempts on this:
1. use brew python, install wxPython also via brew
2. try to resolve what seems to be a font related issue

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
