### ISSUE TITLE
Make current character visible (when horizontally scrolled away) while typing

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#86] opened 2023-11-06 09:17 UTC
After #84 implements horizontal scrolling, you can scroll the current character out of the visible area horizontally. When doing so, starting to type (and other situations that should make the current character visible) don't change the horizontal scrolling.

This should be fixed by turning the `makeLineVisible` function into a `makeCharacterVisible` function and adjusting all usages.

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
