### ISSUE TITLE
Port creation of installables/packages away from distutils

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#75] opened 2023-06-28 14:32 UTC
The `setup.py` script, which  can be used to install Trelby to `/opt` and creates our .rpm and .deb packages and (in theory) our windows installer uses the Python module distutils. Distutils is deprecated and is going to be removed in Python 3.12. If we want to support Python 3.12, we need to get rid of distutils.

If we are going to implement #11, #54 and #62 without `distutils` in the first place, we'll only need to care about rpm, deb and installation to  `/opt`. We might consider dropping support for all these in favour of #54 – in this case, no porting would be needed.

**Comment by limburgher** [comment] 2023-06-28 14:52
We need to continue to support the python build process. If we move from setup.py to setup.cfg and pyproject.toml, we can continue with all planned targets. We need to continue to support rpm and deb at minimum and the python build process makes that easier.

**Comment by janopae** [comment] 2023-06-28 19:08
Ok, I found a migration guide and might be able to port it over to setuptools: https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
