### ISSUE TITLE
Features request.

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#6] opened 2021-03-01 22:45 UTC
Wishlist of features I'd like to see in Trelby in the future (so that other users might add their two cents).

1) Change the default position of pop-up windows (search & replace, go to page, go to scene, etc.) so that they do not cover the text on the page. Ideally, a window should 'remember' the last position when activated again.
2) Autosave.
3) Allow italics, bold, and underlined for single words in action/description and dialogue.
4) Add cour10p_r.ttf fonts to resources (they can be downloaded from trelby.org) and makes them default for exported PDF since they dramatically improve the look and readability of the scripts.
5) Allow selected/copied text to be pasted into the search & replace window. This would be very useful when the words to be searched/replaced include special characters. (Presently, a workaround to this nuisance is to select the text, copy it to the system from the edit menu, and then paste it in the search & replace window).

**Comment by maccagnan** [comment] 2021-05-11 18:01
I post this because I found this tip from @allaboutmikey particularly useful, and someone who doesn't know about it might stumble upon it here.
It regards keyboard shortcuts for desirable features, in my case for system copy/paste.
@allaboutmikey answer was:
This is already possible.
Go into menu: File, Settings, Change
Choose Keyboard from the list on the left.
Choose the commands you want, then assign keys to them.
The commands you probably want are:
CopySystemCb, CopySystemCbFormatted, PasteSystemCb

**Comment by janopae** [comment] 2022-10-25 09:50
Hi @maccagnan! I think your feature requests sound very reasonable and nice to have. Could you submit them again as separate issues, with titles that give a hint want the issues are about? That would help a lot with discussing them and prioritising them.

If I wanted to close this issue, I had to implement 5 non-trivial features, which already sounds so much I don't feel like I want to start :D

**Comment by maccagnan** [comment] 2022-10-25 17:56
Hi @janopae, I cut down the requests to three, since two of them has been addressed separately already, and re-posted them. Thanks for the suggestion.

**Comment by limburgher** [comment] 2023-11-22 16:53
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:45 UTC
