### ISSUE TITLE
Use mypy for static type checking

### ISSUE THREAD

**Issue by janopae** [limburgher/trelby#73] opened 2023-04-07 13:30 UTC
Type declarations in python are not checked by default: They do nothing other than serving documentation purposes, making it easier for the reader (or additional tooling, like an IDE) to understand an interface. Without additional tooling, nothing checks whether type information is correct, and whether interfaces are correctly used based on that information.

In the past, we already had problems caused by type declarations being wrong or outdated, which could have been prevented with static type checking (e. g. #69). That's why @jonafato proposed to add `mypy` to check for types.

**Comment by jonafato** [comment] 2023-04-07 20:22
@janopae Thanks for the mention, I've been meaning to file an issue about adopting mypy. I'm in favor of static type checking in general, both as a type of testing and as a means for making the code base easier / more quick to understand.

I'm happy to put together or help with a first pass of an implementation here. A good starting point would be along the lines of:

1. Add a mypy configuration (and supporting tooling such as a new GitHub Actions job), most likely using "strict" mode.
2. Ignore type checking on most or all of the files in the initial PR
3. Remove the `type: ignore` instructions from files one by one, starting with the places that are already using type annotations

As this process progresses, the balance will shift toward more type checked than not, and any remaining `type: ignore` comments can be handled with more granularity. This approach will let the project begin the type checking process without adding more untyped files to the code base. There will be some additional nuance here (e.g. dealing with untyped third-party libraries), but mypy is definitely worth the investment in my experience.

**Comment by limburgher** [comment] 2023-11-22 16:56
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
