### ISSUE TITLE
Autosave.

### ISSUE THREAD

**Issue by maccagnan** [limburgher/trelby#41] opened 2022-10-25 17:51 UTC
Suggested improvement.
Autosave would spare writers some harsh experiences (especially to those who use laptops with unreliable batteries).

**Comment by Cerabbite** [comment] 2022-12-05 15:22
I would like to take a stab at this

**Comment by limburgher** [comment] 2022-12-05 15:28
Be my guest, pull requests welcome!

**Comment by Cerabbite** [comment] 2022-12-14 07:04
@limburgher Is there a way for me too check whether or not the file the user is currently working on is already saved or not?

**Comment by limburgher** [comment] 2022-12-14 15:49
My suggestion would be to check the size of list of undo items.

**Comment by Cerabbite** [comment] 2022-12-18 09:57
Do I have to put the toggle to turn autosave on or off in here?
![image](https://user-images.githubusercontent.com/98265679/208291933-5582bcd1-4344-429c-a2b6-5641b3d47d34.png)
If so do you by any chance know in which file I have to look in order to add that?

**Comment by limburgher** [comment] 2022-12-21 20:47
That's the config dialog for individual scripts. It should be a global preference.

**Comment by Cerabbite** [comment] 2023-01-16 10:04
> My suggestion would be to check the size of list of undo items.

Do you know where I could find this in the code?

And how could I access config variables?

**Comment by limburgher** [comment] 2023-01-17 19:21
I'm not sure of either at the moment.

**Comment by Cerabbite** [comment] 2023-01-21 08:24
I think I should be able to call https://github.com/limburgher/trelby/blob/main/src/undo.py#L125 to get how much memory is used, and then autosave based upon that.

**Comment by janopae** [comment] 2023-03-11 17:25
> I think I should be able to call https://github.com/limburgher/trelby/blob/main/src/undo.py#L125 to get how much memory is used, and then autosave based upon that.

I don't really think that works, as this method gives you the memory a *specific* undo action takes. But what you need is the *number* of actions on the stack.

What do you need the information whether the current file has been saved for? Maybe we can find a better solution.

**Comment by Cerabbite** [comment] 2023-03-11 21:07
The way I currently do it is with this function:
```Python
def autosave(self):
        if self.fileName:
            self.saveFile(self.fileName)
        wx.CallLater(3000, self.autosave)
```

This autosave the file every 3 seconds when the file is saved however I think a better solution would be to instantly save the file when a change is made. And I presume that the size of ```undo``` changes when a change to the file is made. So I only need the ```undo``` size to know when a change is made.

**Comment by janopae** [comment] 2023-03-12 17:45
> This autosave the file every 3 seconds when the file is saved however I think a better solution would be to instantly save the file when a change is made. And I presume that the size of undo changes when a change to the file is made. So I only need the undo size to know when a change is made.

Thanks, now I understand! When I thought about how to implement this, I also thought about triggering the autosave whenever a change is made.

However, triggering the autosave on every change would trigger a save operation on every keystroke. As that would be too much for such a resource heavy operation, I thought about debouncing it. That essentially means that when something changed (e. g. a key has been pressed), we start a timer with a little timeout (a fraction of a second), and when a new change comes and the timer hasn't finished yet, we just restart the timer. This way, it wouldn't save constantly while typing, but only in the short breaks that last longer than our timeout (e. g. 300 ms). I think this should be achievable with `wx.CallLater`.

I looked into the code, and I found out that changing the document state is not exactly the same as creating an undo item. Sometimes, undo items won't be created for certain operations, but it's still a change on the document that we want to save. But there is a method called `markChanged` that is called every time the screenplay is changed and that saves whether the screenplay has been changed for the "Are you sure you want to exit?" prompt. I think this is much closer to what we mean when we talk about when a screenplay is changed.

You could either replace all function calls for `markChanged` with firing an event, to which you then would subscribe both, `markChanged` and your autosave function, or you could just rename `markChanged` to something more abstract (like `changed`) and call your autosave function from it/reset the timer that calls it.

PS: If you need any help with this, don't hesitate to ask me!

**Comment by Cerabbite** [comment] 2023-03-13 06:47
> But there is a method called ```markChanged``` that is called every time the screenplay is changed

This was the function I was looking for, I will update my code in the coming days.

**Comment by Cerabbite** [comment] 2023-03-14 22:22
I just tried adding autosave using ```markChanged```, but since ```markChanged``` is in ```screenplay.py``` and ```self.fileName``` in ```trelby.py``` I always get issues with not being able to access ```self.fileName```. I use ```self.fileName``` to check if a file has already been saved, so it does not try to save a file that has not yet been saved as this would bring up a file dialog window. Any suggestions?

This is the [PR](https://github.com/Cerabbite/trelby/tree/autosave-markchanged)

**Comment by janopae** [comment] 2023-03-15 23:54
Thanks! I'll try to look into this at the weekend.

PS: Could you create a Draft PR against `limburgher/trelby`? That would make it much easier for me to comprehend your changes.

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
