### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by MistahMojo** [limburgher/trelby#11] opened 2021-04-02 03:17 UTC
Hi, good to see a serious effort to get Trelby up to date and maintained again.

I'm more than happy to try and get a Windows version happening - currently when I try to pip in requirements I'm getting an error as it tries to absolute into `\opt\trelby\`, which obviously doesn't work on Windows.

Where to start?

**Comment by limburgher** [comment] 2021-04-02 13:41
Hmm. At least pip install -f requirements.txt should work. After a lot of effort on a test Windows box I was able to get Trelby working. My goal is to provide an installer here, and there's an install.nsi, but I'm very green on Windows software packaging.

**Comment by limburgher** [comment] 2021-04-02 14:25
I know also that the build should be create with the build.bat script, which obviates the /opt/trelby issue.

**Comment by MistahMojo** [comment] 2021-04-03 07:46
```ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 240, in run
    options.use_user_site = decide_user_install(
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 648, in decide_user_install
    if site_packages_writable(root=root_path, isolated=isolated_mode):
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 593, in site_packages_writable
    get_lib_location_guesses(root=root, isolated=isolated))
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\commands\install.py", line 584, in get_lib_location_guesses
    scheme = distutils_scheme('', user=user, home=home, root=root,
  File "C:\Users\...\AppData\Roaming\Python\Python39\site-packages\pip\_internal\locations.py", line 115, in distutils_scheme
    i.finalize_options()
  File "c:\python39\lib\distutils\command\install.py", line 345, in finalize_options
    self.convert_paths('lib', 'purelib', 'platlib',
  File "c:\python39\lib\distutils\command\install.py", line 488, in convert_paths
    setattr(self, attr, convert_path(getattr(self, attr)))
  File "c:\python39\lib\distutils\util.py", line 123, in convert_path
    raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/opt/trelby' cannot be absolute
```

Running Pip 21.0.1 and Python 3.9. The .bat would be useful, IF I can get the deps installed!

Interestingly enough, setting up a venv and running the commands in that yields a different error:
```ERROR: Could not find a version that satisfies the requirement requirements.txt
ERROR: No matching distribution found for requirements.txt
```
Installing wx and lxml individually works fine this way.

**Comment by limburgher** [comment] 2021-04-05 13:58
I meant pip install -r requirements.txt. E_COFFEE

**Comment by Cerabbite** [comment] 2022-12-18 14:34
I tried to build for windows today but I got this error.

```
Traceback (most recent call last):
  File "setup.py", line 171, in <module>
    setup(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\distutils_buildexe.py", line 188, in run
    self._run()
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\distutils_buildexe.py", line 267, in _run
    builder.analyze()
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\runtime.py", line 160, in analyze
    self.mf.import_hook(modname)
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\mf3.py", line 120, in import_hook
    module = self._gcd_import(name)
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\mf3.py", line 274, in _gcd_import
    return self._find_and_load(name)
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\mf3.py", line 357, in _find_and_load
    self._scan_code(module.__code__, module)
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\mf3.py", line 388, in _scan_code
    for what, args in self._scan_opcodes(code):
  File "C:\Users\[user]\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\py2exe\mf3.py", line 417, in _scan_opcodes
    yield "store", (names[oparg],)
IndexError: tuple index out of range
```

And then this one
```
running nsis
Traceback (most recent call last):
  File "setup.py", line 103, in run
    regPathKey = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r"Software\NSIS")
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 171, in <module>
    setup(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 109, in run
    raise Exception("There was an error reading the registry key for NSIS.\n"
Exception: There was an error reading the registry key for NSIS.
You may need to reinstall NSIS to fix this error.
```

**Comment by janopae** [comment] 2023-03-11 17:32
Hey @Cerabbite, according to the screenshots you posted in #46, you seem to have gotten this to work on Windows, haven't you? It would be extremely nice if we had working instructions in the README, and at best a working way to build a Setup.exe for Windows.

Do you think you could contribute to these things?

**Comment by Cerabbite** [comment] 2023-03-11 21:00
I unfortunatly have not been able to build it to exe on windows. Once I have some more time on my hands I'll take another look at it

**Comment by limburgher** [comment] 2023-11-22 16:54
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-12-22 19:46 UTC
