### ISSUE TITLE
Ability to run in headless mode

### ISSUE THREAD

**Issue by mwchase** [limburgher/trelby#17] opened 2022-03-09 03:33 UTC
Motivation: out of all of the free tools I've tried to work with fountain files, trelby had the nicest PDF output, so if I *can* fit it into a pipeline with a call like `trelby-cli input.fountain --pdf output.pdf` (details subject to change), I'd like to.

But, this is, given my brief look at the import code, not easy. It kind of all assumes it's running inside wxPython.
To accomplish this, I'd want to separate out code into "frontend" (CLI, wx) and "backend" (all of the stuff that shouldn't be concerned with UI)

I'm willing to put in the effort to make this happen, but I'd really like to know if anyone else is interested in such a project, and I want to make sure that any efforts along those lines don't interfere with any other work, since the required changes are pretty invasive.

**Comment by limburgher** [comment] 2022-03-15 21:08
This is absolutely something others are interested in. If you'd like to work on it, be my guest!

**Comment by janopae** [comment] 2022-09-01 16:05
This is what I think we have to do in order to resolve this issue:

- [ ] Make import independent from wxWindows
    - [ ] Implement tests for import
        - [x] Test text import #27
        - [x] Test celtx import #30
        - [ ] Test Fountain import
        - [ ] Test Fadein import
        - [ ] Test Astx import
        - [ ] Test FDX import
    - [ ] Refactor the wxWindows dependency out of the import
- [ ] Make screenplay model independent from wxWindows
- [ ] Make export independent from wxWindows
- [ ] Design and implement a CLI with import and export capabilities

**Comment by juliaclement** [comment] 2022-09-19 10:08
I don't know if this is any use to anyone, but I've been building a pair of fountain <-> Libreoffice converters. Once converted, it can run LibreOffice headless to print the document to PDF. https://github.com/juliaclement/screenwriting

**Comment by limburgher** [comment] 2022-09-19 20:09
Fascinating, thank you for sharing!

**Comment by limburgher** [comment] 2023-11-22 16:55
Hello! This repository is merging into https://github.com/trelby/trelby.

Please check your issue against the current code there. If the issue is still relevant, please open a version of this issue there and close this issue. If not, just close this issue.

All issues in this repository that are still open in 30 days will be closed. Thank you!

**Closed as completed** 2023-11-22 17:38 UTC
